// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynthcbbquqljxpmagupy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InludGhjYmJxdXFsanhwbWFndXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NDc2MDcsImV4cCI6MjA1OTEyMzYwN30.YiV_VTW-CGz6VBCcxsXZ3rVoVyOYmc77Y1YW1EUWyh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);